name: ender_chest
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0-245.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  window_manager: ^0.3.0
  hotkey_manager: ^0.1.7
  system_theme: ^2.1.0
  clipboard_watcher: ^0.1.3
  super_clipboard: ^0.2.1+1
  tray_manager: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
